#define diffusion_POOL1 0
#define diffusion_POOL2 1
#define rxnpool_RXN0 0
#define rxnpool_RXN1 1
#define rxnpool_RXN2 2
#define rxnpool_RXN2MOLES 3
#define rxnpool_CURRENT 4
#define rxnpool_RXN0MOLES 5
#define rxnpool_VOLUME 6
#define cicr_ASTATE 0
#define cicr_BSTATE 1
#define cicr_GSTATE 2
#define cicr_IP3 3
#define cicr_CALCIUM 4
#define cicr_CONSERVE 5
#define cicrflux_CONC1 0
#define cicrflux_CONC2 1
#define cicrflux_IP3R 2
#define enzyme_ENZ 0
#define enzyme_FEEDBACK 1
#define enzyme_SUBSTRATE 2
#define enzyme_RHODOPSIN 3
#define enzyme_VOLUME 4
#define mmenz_ENZ 0
#define mmenz_FEEDBACK 1
#define mmenz_SUBSTRATE 2
#define feedback_CONC 0
#define rhodopsin_ISOM 0
#define rhodopsin_INACT 1
#define mmpump2_CONC 0
#define ncx_CAINT 0
#define ncx_CAEXT 1
#define ncx_NAINT 2
#define ncx_NAEXT 3
#define ncx_VM 4
#define reaction_SUBSTRATE 0
#define reaction_PRODUCT 1
#define conservepool_CONC 0
#define conservepool_MOLES 1
#define conservepool_VOLUME 2
#define wgtavg_ValueWgt 0
